services:
  dynamodb:
    image: amazon/dynamodb-local:2.6.0
    container_name: dynamodb
    ports:
      - '8000:8000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]',
        ]
      interval: 3s
      timeout: 10s
      retries: 10
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    depends_on:
      dynamodb:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
    entrypoint:
      - /bin/sh
      - -c
      - aws dynamodb create-table --endpoint-url "http://dynamodb:8000" --table-name customers --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
